config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "boards#index"
  resources :boards, only: [:new, :create, :show]
  get 'all_boards', to: 'boards#all'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :width, :height, :mines_count, :name, :email, presence: true
  serialize :board_state, JSON
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @recent_boards = Board.order(created_at: :desc).limit(10)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.board_state = MinesweeperService.generate_board(@board.width, @board.height, @board.mines_count)

    if @board.save
      redirect_to @board, notice: 'Board was successfully created.'
    else
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def all
    @boards = if params[:search].present?
                Board.where('name LIKE ? OR email LIKE ?',
                  "%#{params[:search]}%",
                  "%#{params[:search]}%")
                  .paginate(page: params[:page], per_page: 10)
              else
                Board.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
              end
  end

  private

  def board_params
    params.require(:board).permit(:width, :height, :mines_count, :name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board_info.html.erb
<li>
  <%= link_to board.name, board_path(board) %>
  <p class="extra_board_info">By: <%= board.email %> @ <%= board.created_at.strftime("%d %b %Y %H:%M") %></p>
</li>

app/views/boards/all.html.erb
<h1>All Boards</h1>
<%= form_tag all_boards_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by email or board name" %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<ul>
  <%= render partial: 'board_info', collection: @boards, as: :board %>
</ul>

<%= will_paginate @boards %>

<div class="row show_breadcrums">
  <%= link_to 'Home', root_path, class: 'btn btn-secondary' %> | <%= link_to 'Create New Board', new_board_path, class: 'btn btn-primary' %>
</div>

app/views/boards/index.html.erb
<h1>Recent Boards</h1>


<ul>
  <%= render partial: 'board_info', collection: @recent_boards, as: :board %>
</ul>

<div class="row">
  <%= link_to 'Create New Board', new_board_path, class: 'btn btn-primary' %> | <%= link_to 'View all generated boards', all_boards_path, class: 'btn btn-info' %>
</div>

app/views/boards/new.html.erb
<h1>Create a New Board</h1>

<%= form_with(model: @board, local: true) do |form| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :board_name %>
    <%= form.text_field :name, id: :board_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :board_email %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width, id: :board_width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, id: :board_height %>
  </div>

  <div class="field">
    <%= form.label :mines_count %>
    <%= form.number_field :mines_count, id: :board_mines_count %>
  </div>

  <div class="actions">
    <%= form.submit "Generate Board" %>
  </div>
<% end %>

<div class="row show_breadcrums">
  <%= link_to 'Home', root_path, class: 'btn btn-secondary' %> | <%= link_to 'View all generated boards', all_boards_path, class: 'btn btn-info' %>
</div>

app/views/boards/show.html.erb
<h1 class="no_padding"><%= @board.name %></h1>
<p class="extra_board_info">By: <%= @board.email %> @ <%= @board.created_at.strftime("%d %b %Y %H:%M") %></p>

<div class="minesweeper-board">
  <% @board.board_state.each do |row| %>
    <div class="minesweeper-row">
      <% row.each do |cell| %>
        <div class="minesweeper-cell">
          <% if cell == 'X' %>
            <i class="fas fa-bomb mine-color"></i>
          <% else %>
            <i class="fas fa-square"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="row show_breadcrums">
  <%= link_to 'Home', root_path, class: 'btn btn-secondary' %> | <%= link_to 'View all generated boards', all_boards_path, class: 'btn btn-info' %> |  <%= link_to 'Create New Board', new_board_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinesweeperApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>